### ISSUE TITLE
merging minijasminenode options

### ISSUE THREAD

**Issue by searls** [testdouble/grunt-jasmine-bundle#5]
Hey @jasonkarns -- I swear this used to work but I'm also a crazy person. Either way I'd really like it to work. Dumping it here while I keep working on lineman:

I'd like the target-level options to extend the task-level options like so:

```
    spec:
      options:
        minijasminenode:
          showColors: true

      e2e:
        options:
          minijasminenode:
            onComplete: (runner, log) ->
              browser?.quit()
```

Such that what gets passed to minijasminenode as the config contains both the `onComplete` and the `showColors`. Right now it's just shallow-ly overwriting `showColors` in this case.
